name: Build and Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Framework SDK
      uses: warrenbuckley/Setup-NET-Framework@v1
      with:
        dotnet-version: '4.7.2'

    - name: Build project
      run: msbuild DataArray/DataArray.csproj /p:Configuration=Debug

    - name: Upload DataArray.exe
      uses: actions/upload-artifact@v2
      with:
        name: DataArray Executable
        path: DataArray/bin/Debug/DataArray.exe
